# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-17 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('wechat', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
